# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dbconnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector as mc
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 20, 350, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 119, 391, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCreate = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnCreate.setObjectName("btnCreate")

        self.btnCreate.clicked.connect(self.create_database)
        self.horizontalLayout_2.addWidget(self.btnCreate)
        self.btnConnect = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnConnect.setObjectName("btnConnect")
        
        self.btnConnect.clicked.connect(self.db_connect)
        self.horizontalLayout_2.addWidget(self.btnConnect)
        self.labelInfo = QtWidgets.QLabel(Form)
        self.labelInfo.setGeometry(QtCore.QRect(60, 200, 300, 20))
        self.labelInfo.setObjectName("labelInfo")
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelInfo.setFont(font)
        self.labelInfo.setObjectName("labelInfo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def create_database(self):
        try:
            mydb = mc.connect(
                host = 'localhost',
                user = 'root',
                password = ''
            )
            cursor = mydb.cursor()
            dbname = self.lineEdit.text()
            cursor.execute('CREATE DATABASE {}'.format(dbname))
            self.labelInfo.setText("Database {} Created ".format(dbname))
        except mc.Error as e:
            print('Error creating database: ', e)
            self.labelInfo.setText("Database creation failed!")

    def db_connect(self):
        try:
            mydb = mc.connect(
                host = 'localhost',
                user = 'root',
                password = ''
            )
            self.labelInfo.setText("Connected")
        except mc.Error as err:
            self.labelInfo.setText(f"Connection failed:", err)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CREATE DATABASE"))
        self.btnCreate.setText(_translate("Form", "DATABASE CREATION"))
        self.btnConnect.setText(_translate("Form", "DATABASE CONNECTION"))
        self.labelInfo.setText(_translate("Form", "TextLabel"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())